# Generated by Django 5.2.1 on 2025-05-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('shorten_url', models.CharField(max_length=10, unique=True)),
                ('created_now', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
